INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, STOCK, PRICE) VALUES (1, 'Book 1', 'Riley Bakes', 5, 15.00);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, STOCK, PRICE) VALUES (2, 'Book 2', 'Riley Bakes', 1, 15.00);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, STOCK, PRICE) VALUES (3, 'Book 3', 'Riley Bakes', 3, 15.00);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR, STOCK, PRICE) VALUES (4, 'Book A', 'Seth Bakes', 2, 25.00);
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME) VALUES (1, 'Jane Doe');
INSERT INTO CUSTOMER (CUSTOMER_ID, NAME) VALUES (2, 'Joe Guy');