INSERT INTO BOOK (TITLE, AUTHOR, STOCK, PRICE) VALUES ('Book 1', 'Riley Bakes', 5, 15.00);
INSERT INTO BOOK (TITLE, AUTHOR, STOCK, PRICE) VALUES ('Book 2', 'Riley Bakes', 1, 15.00);
INSERT INTO BOOK (TITLE, AUTHOR, STOCK, PRICE) VALUES ('Book 3', 'Riley Bakes', 3, 15.00);
INSERT INTO BOOK (TITLE, AUTHOR, STOCK, PRICE) VALUES ('Book A', 'Seth Bakes', 2, 25.00);
INSERT INTO CUSTOMER (NAME) VALUES ('Jane Doe');
INSERT INTO CUSTOMER (NAME) VALUES ('Joe Guy');